version: '3'

services:
  # sync devcontainer.json 'service'
  python3:
    # original container naame
    container_name: emergency-bot-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    tty: true
    # working dir
    working_dir: /workspace
    # setting volume (host:container)
    volumes:
      - ..:/workspace
